name: Build
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Build
        uses: espressif/esp-idf-ci-action@v4.3
      - name: Zip binaries
        run: zip --junk-paths binaries build/hello-world.bin build/bootloader/bootloader.bin build/partition_table/partition-table.bin 
      - name: Prepare artifact
        uses: actions/upload-artifact@v2
        with:
          path: binaries.zip